#ifndef QREDMINECLIENT_GLOBAL_H
#define QREDMINECLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QREDMINECLIENT_LIBRARY)
#  define QREDMINECLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QREDMINECLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QREDMINECLIENT_GLOBAL_H
